---

- include: pkg.yml
  when: ansible_os_family == "FreeBSD" and autologic_osupdate_use_pkg_freebsd
  tags: autologic_osupdate_play_freebsd_pkg

- include: ports.yml
  when: ansible_os_family == "FreeBSD" and autologic_osupdate_use_ports_freebsd
  tags: autologic_osupdate_play_freebsd_ports

- include: security.yml
  when: ansible_os_family == "FreeBSD" and autologic_osupdate_manage_security_freebsd
  tags: autologic_osupdate_play_freebsd_security
