---

- name: Update everything using PKG (FreeBSD)
  command: /usr/sbin/pkg upgrade -y
  register: update_result
  changed_when: "'Your packages are up to date.' not in update_result.stdout"
  tags: autologic_osupdate_task_update_pkg_freebsd
